FROM tlinnet/relax:01_packages

# Possible minimise install
# https://www.dajobe.org/blog/2015/04/18/making-debian-docker-images-smaller/

# For python2+3
ENV PIP_PACKAGES="epydoc mpi4py numpy==1.12.1 scipy matplotlib pandas jupyter jupyterlab ipykernel"

# Install. Upgrade pip in special order, so pip does not become pip3. Sigh...
RUN echo "" && \
    pip install setuptools && \
    pip3 install --upgrade pip && \
    pip3 install setuptools && \
    pip2 install --upgrade pip && \
    pip install $PIP_PACKAGES && \
    pip3 install $PIP_PACKAGES && \
    ipython2 kernel install && \
    ipython3 kernel install && \
    jupyter serverextension enable --py jupyterlab --sys-prefix

# Install relax python pagkages
# current version of minfx and bmrblib and nmrglue
RUN echo "" && \
    VMIN=`lynx -dump "http://wiki.nmr-relax.com/Template:Current_version_minfx" | grep -A 10 "Template:Current version minfx" | grep -B 1 "Retrieved from" | head -n 1 | tr -d '[[:space:]]'` && \
    echo "Installing current version of minfx: $VMIN" && \
    pip install https://iweb.dl.sourceforge.net/project/minfx/$VMIN/minfx-$VMIN.tar.gz && \
    pip3 install https://iweb.dl.sourceforge.net/project/minfx/$VMIN/minfx-$VMIN.tar.gz && \
    echo "" && \
    VBMR=`lynx -dump "http://wiki.nmr-relax.com/Template:Current_version_bmrblib" | grep -A 10 "Template:Current version bmrblib" | grep -B 1 "Retrieved from" | head -n 1 | tr -d '[[:space:]]'` && \
    echo "Installing current version of bmrblib: $VBMR" && \
    pip install https://iweb.dl.sourceforge.net/project/bmrblib/$VBMR/bmrblib-$VBMR.tar.gz && \
    pip3 install https://iweb.dl.sourceforge.net/project/bmrblib/$VBMR/bmrblib-$VBMR.tar.gz && \
    echo "" && \
    NGLUE=`curl -s https://api.github.com/repos/jjhelmus/nmrglue/releases/latest | grep "browser_download_url" | cut -d: -f2,3 | tr -d \" ` && \
    echo "Installing current version of nmrglue: $NGLUE" && \
    pip install $NGLUE && \
    pip3 install $NGLUE
