FROM tlinnet/relax:05

# Add mmass
# http://mmass.org/
# http://forum.mmass.org/viewtopic.php?id=1507
RUN cd $HOME && \
    echo "mmass" && \
    mkdir -p $HOME/Downloads && \ 
    cd $HOME/Downloads && \ 
    version=v5.5.0 && \ 
    mfile=mmass_${version}_source.zip && \ 
    curl -O http://www.mmass.org/download/files/$version/$mfile && \ 
    unzip $mfile && \ 
    cd ./mMass/mspy && \ 
    python setup.py build && \ 
    find ./build -iname 'calculations.so' -type f | xargs -I '{}' mv '{}' . && \
    cd .. && \
    curl -O https://gist.githubusercontent.com/tlinnet/44887c3056f33314f432cd35fe222ee0/raw/a5d20bb2e3070060bfe210a1ebdebe5f2c646cfc/0001-Made-pathches-to-get-mMass-5.5.0-to-work-on-wxPython.patch && \ 
    git apply 0001-Made-pathches-to-get-mMass-5.5.0-to-work-on-wxPython.patch && \ 
    cd $HOME && \
    mv $HOME/Downloads/mMass $HOME/software/mMass && \
    cd $HOME/bin && \
    echo "#!/usr/bin/env bash" > mmass && \
    echo "python $HOME/software/mMass/mmass.py" >> mmass && \
    chmod +x mmass
