FROM tlinnet/relax:01_packages

################################
# Only for: FROM jupyter/scipy-notebook
################################
# For pre-installed packages, see: 
# https://hub.docker.com/r/jupyter/scipy-notebook
# pandas, matplotlib, scipy, seaborn, scikit-learn, 
# scikit-image, sympy, cython, patsy, statsmodel, cloudpickle, 
# dill, numba, bokeh, vincent, beautifulsoup, xlrd pre-installed

# Set variables    
ENV NB_USER jovyan
# Set user
USER ${NB_USER}

ENV ANACONDA_PACKAGES="mpi4py pyside wxpython"
ENV PIP_PACKAGES="epydoc scons nmrglue"
# For relax, minfx, bmrblib
ENV PIP_PACKAGES="$PIP_PACKAGES https://iweb.dl.sourceforge.net/project/minfx/1.0.12/minfx-1.0.12.tar.gz"
ENV PIP_PACKAGES="$PIP_PACKAGES https://iweb.dl.sourceforge.net/project/bmrblib/1.0.4/bmrblib-1.0.4.tar.gz"

# Install
RUN echo "" && \
    conda install -c anaconda $ANACONDA_PACKAGES  && \
    pip install $PIP_PACKAGES

################################
# Only for: FROM jupyter/scipy-notebook
# Python2.7 for some programs
################################
# Create virtual env
# 'anaconda' is the metapackage that includes all of the Python packages comprising the Anaconda distribution
RUN echo "" && \
    conda create -y -n python27 python=2.7 anaconda

# Get packages for MddNMR
ENV ANACONDA_PACKAGES27="pyside numpy"

# Get packages for mmass and relax
ENV ANACONDA_PACKAGES27="$ANACONDA_PACKAGES27 wxpython"

# Get packages for relax
ENV ANACONDA_PACKAGES27="$ANACONDA_PACKAGES27 mpi4py"
ENV CONDAFORGE_PACKAGES27="matplotlib scipy"
ENV PIP_PACKAGES27="epydoc scons nmrglue"
ENV PIP_PACKAGES27="$PIP_PACKAGES27 https://iweb.dl.sourceforge.net/project/minfx/1.0.12/minfx-1.0.12.tar.gz"
ENV PIP_PACKAGES27="$PIP_PACKAGES27 https://iweb.dl.sourceforge.net/project/bmrblib/1.0.4/bmrblib-1.0.4.tar.gz"

# Install
RUN echo "" && \
    conda install -y -n python27 -c anaconda $ANACONDA_PACKAGES27 && \
    conda install -y -n python27 -c conda-forge $CONDAFORGE_PACKAGES27 && \
    /bin/bash -c "source activate python27; python -m pip install $PIP_PACKAGES27"