FROM tlinnet/relax:02_python

################################
# Only for: FROM jupyter/scipy-notebook
################################
# Set variables    
ENV NB_USER jovyan
ENV NB_UID 1000
# Set user
USER ${NB_USER}
ENV HOME=/home/${NB_USER}
WORKDIR /home/jovyan/work
ENV PATH="$HOME/bin:${PATH}"

# Make default folders
# Stop Gtk-WARNING with .local/share
RUN echo "" && \
    mkdir -p $HOME/.local/share && \
    mkdir -p $HOME/bin && \
    mkdir -p $HOME/software

# jupyter notebook password remove
RUN echo "" && \
    mkdir -p $HOME/.jupyter && \
    cd $HOME/.jupyter && \
    echo "c.NotebookApp.token = u''" > jupyter_notebook_config.py
