FROM tlinnet/relax:05

# Add mmass
# http://mmass.org/
# http://forum.mmass.org/viewtopic.php?id=1507
RUN cd $HOME && \
    echo "mmass" && \
    mkdir -p $HOME/Downloads && \ 
    cd $HOME/Downloads && \ 
    version=v5.5.0 && \ 
    mfile=mmass_${version}_source.zip && \ 
    curl -O http://www.mmass.org/download/files/$version/$mfile && \ 
    unzip $mfile && \ 
    cd ./mMass/mspy && \ 
    python setup.py build && \ 
    find ./build -iname 'calculations.so' -type f | xargs -I '{}' mv '{}' . && \
    cd .. && \
    curl -O https://gist.githubusercontent.com/tlinnet/44887c3056f33314f432cd35fe222ee0/raw/a5d20bb2e3070060bfe210a1ebdebe5f2c646cfc/0001-Made-pathches-to-get-mMass-5.5.0-to-work-on-wxPython.patch && \ 
    git apply 0001-Made-pathches-to-get-mMass-5.5.0-to-work-on-wxPython.patch && \ 
    cd $HOME && \
    mv $HOME/Downloads/mMass $HOME/software/mMass && \
    cd $HOME/bin && \
    echo "#!/usr/bin/env bash" > mmass && \
    echo "python $HOME/software/mMass/mmass.py" >> mmass && \
    chmod +x mmass

# Fix according to http://forum.mmass.org/viewtopic.php?id=274
RUN cd $HOME && \
    cd $HOME/software/mMass && \
    curl -O https://gist.githubusercontent.com/tlinnet/2c3c4e65e91a3f338ca93487c282f932/raw/e987c03c0abc9ba62ff86a7d47c7d00d99efb132/0001-Making-patch-according-to-http-forum.mmass.org-viewt.patch && \
    git apply 0001-Making-patch-according-to-http-forum.mmass.org-viewt.patch && \
    echo ""

# Convert massspec files
# https://hub.docker.com/r/suchja/wine/
# https://github.com/phnmnl/container-pwiz
# https://github.com/sneumann/pwiz-appliance
# https://github.com/jmchilton/proteomics-wine-env
# https://github.com/BioContainers/specs/issues/64
