FROM tlinnet/relax:02

# Add user: After this, no installing to system directories is possible.
# Unless setting: USER root
# -m : Create the home directory if it does not exist.
# -s : User's login shell, which defaults to /bin/bash
RUN useradd -ms /bin/bash developer && \
    adduser developer sudo && \
    echo "developer:passwd" | chpasswd && \
    mkdir -p $HOME/.local/share && \
    mkdir -p $HOME/bin && \
    mkdir -p $HOME/software
USER developer
# Stop Gtk-WARNING with .local/share
RUN mkdir -p $HOME/work && \
    mkdir -p $HOME/.local/share && \
    mkdir -p $HOME/bin && \
    mkdir -p $HOME/software
WORKDIR /home/developer/work
ENV HOME=/home/developer
ENV PATH="$HOME/bin:${PATH}"

# jupyter notebook password
RUN echo "" && \
    mkdir -p $HOME/.jupyter && \
    cd $HOME/.jupyter && \
    echo "{" > jupyter_notebook_config.json && \
    echo "  "NotebookApp": {" >> jupyter_notebook_config.json && \
    echo "    "password": "sha1:44a0c66870f6:232a4f58dc227666515f06edd5b2a408c499c2fb"" >> jupyter_notebook_config.json && \
    echo "  }" >> jupyter_notebook_config.json && \
    echo "}" >> jupyter_notebook_config.json
