# Docker info: https://docs.docker.com/engine/userguide/eng-image/dockerfile_best-practices/

# Possible minimise install: https://www.dajobe.org/blog/2015/04/18/making-debian-docker-images-smaller/
# Layering RUN instructions and generating commits conforms to commits are cheap and containers
# can be created from any point in an images history.

# See latest tag at: https://hub.docker.com/r/jupyter/scipy-notebook/
FROM jupyter/scipy-notebook:033056e6d164

# Set root
USER root

# General packages.
ENV BUILD_PACKAGES="lynx htop curl wget unzip tcsh subversion git nano vim gedit"

# For relax. 'python-wxgtk3.0' will be installed with conda.
ENV BUILD_PACKAGES="$BUILD_PACKAGES grace dx scons"
ENV BUILD_PACKAGES="$BUILD_PACKAGES openmpi-bin openmpi-doc libopenmpi-dev"

# NMRPipe
# http://www.lorieau.com/nmr/2015/04/15/NMRPipe-ubuntu14.04.html
# https://www.ibbr.umd.edu/nmrpipe/install.html
RUN dpkg --add-architecture i386
ENV BUILD_PACKAGES="$BUILD_PACKAGES csh libc6:i386 libstdc++6:i386 libx11-6:i386"
ENV BUILD_PACKAGES="$BUILD_PACKAGES libxext6:i386 xfonts-75dpi default-jre default-jdk"

# msttcorefonts has License terms, which needs to be accepted
RUN echo ttf-mscorefonts-installer msttcorefonts/accepted-mscorefonts-eula select true | debconf-set-selections
ENV BUILD_PACKAGES="$BUILD_PACKAGES msttcorefonts"

# For MddNMR. 'pyside' will be installed with conda.
ENV BUILD_PACKAGES="$BUILD_PACKAGES gawk"

# For Palmer: modelfree4 and FastModelFree
ENV BUILD_PACKAGES="$BUILD_PACKAGES libatlas3-base tk"

# Install
RUN echo "Installing these packages" $BUILD_PACKAGES

# Install all packages in 1 RUN
RUN apt-get update && \
    apt-get install --no-install-recommends -y $BUILD_PACKAGES && \
    rm -rf /var/lib/apt/lists/*
