FROM tlinnet/relax:02_python

################################
# Only for: FROM jupyter/scipy-notebook
################################
# Set variables    
ENV NB_USER jovyan
ENV NB_UID 1000
# Set user
USER ${NB_USER}
ENV HOME=/home/${NB_USER}
WORKDIR /home/jovyan/work
ENV PATH="$HOME/bin:${PATH}"

# Make default folders
# Stop Gtk-WARNING with .local/share
RUN echo "" && \
    mkdir -p $HOME/.local/share && \
    mkdir -p $HOME/bin && \
    mkdir -p $HOME/software

# jupyter notebook password remove
RUN echo "" && \
    mkdir -p $HOME/.jupyter && \
    cd $HOME/.jupyter && \
    echo "c.NotebookApp.token = u''" > jupyter_notebook_config.py

################################
# Only for: FROM ubuntu:16.04
################################
## Add user: After this, no installing to system directories is possible.
## Unless setting: USER root
## -m : Create the home directory if it does not exist.
## -s : User's login shell, which defaults to /bin/bash
#RUN useradd -ms /bin/bash developer && \
#    adduser developer sudo && \
#    echo "developer:passwd" | chpasswd && \
#    mkdir -p $HOME/.local/share && \
#    mkdir -p $HOME/bin && \
#    mkdir -p $HOME/software
#USER developer
## Stop Gtk-WARNING with .local/share
#RUN mkdir -p $HOME/work && \
#    mkdir -p $HOME/.local/share && \
#    mkdir -p $HOME/bin && \
#    mkdir -p $HOME/software
#WORKDIR /home/developer/work
#ENV HOME=/home/developer
#ENV PATH="$HOME/bin:${PATH}"

## jupyter notebook password and activation of jupyter-lab
#RUN echo "" && \
#    mkdir -p $HOME/.jupyter && \
#    cd $HOME/.jupyter && \
#    echo "c.NotebookApp.token = u''" > jupyter_notebook_config.py
#    #jupyter serverextension enable --py jupyterlab --user

## Expose to run jupyter notebook
#EXPOSE 8888
